spring.application.name=surequinos-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://yamanote.proxy.rlwy.net:35348/railway?sslmode=require&currentSchema=railway
spring.datasource.username=postgres
spring.datasource.password=XKbmqwCSfuATPwYREkRHbmYoAYGZuZQI
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=railway

# Server Configuration (Railway inyecta PORT; local usa 8080)
server.port=${PORT:8080}
server.servlet.context-path=/api

# Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Logging
logging.level.com.surequinos=DEBUG
logging.level.org.springframework.web=DEBUG

# Cloudflare R2 Configuration
cloudflare.r2.account-id=227387f9907361fb42f2b6d82f368b92
cloudflare.r2.access-key-id=5ba60f953184e678092e4d8cc72ca642
cloudflare.r2.secret-access-key=7746b574318cb1b9385514df7b07e56cd99cf92b943ea3dba4d98d648a25391b
cloudflare.r2.bucket-name=surequinos
cloudflare.r2.region=auto
cloudflare.r2.endpoint=https://227387f9907361fb42f2b6d82f368b92.r2.cloudflarestorage.com
cloudflare.r2.public-url=https://pub-e29c0247fb7649ce98590df7640d058a.r2.dev

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Spring Boot DevTools Configuration
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=src/main/java,src/main/resources
spring.devtools.restart.exclude=static/**,public/**,templates/**